modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/dylanrenwick/super-stick-sword/issues"

[[mods]]
modId="super_stick_sword"
version="${version}"
displayName="Super Stick sword"
displayURL="http://skidsdev.xyz/"
authors="GunnerWolf"
description='''
Super Stick Sword adds a new sword crafted from Octuple-Compressed sticks (which in turn take Septuple-Compressed sticks and so on).

The sword has 2500 durability, and deals 100 damage. Its attack speed is that of a regular sword.
'''
